/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Realsense2Camera
{
    public class Extrinsics : Message
    {
        public const string RosMessageName = "realsense2_camera/Extrinsics";

        public Header header { get; set; }
        public double[] rotation { get; set; }
        public double[] translation { get; set; }

        public Extrinsics()
        {
            this.header = new Header();
            this.rotation = new double[9];
            this.translation = new double[3];
        }

        public Extrinsics(Header header, double[] rotation, double[] translation)
        {
            this.header = header;
            this.rotation = rotation;
            this.translation = translation;
        }
    }
}
