/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Realsense2Camera
{
    public class IMUInfo : Message
    {
        public const string RosMessageName = "realsense2_camera/IMUInfo";

        public string frame_id { get; set; }
        public double[] data { get; set; }
        public double[] noise_variances { get; set; }
        public double[] bias_variances { get; set; }

        public IMUInfo()
        {
            this.frame_id = "";
            this.data = new double[12];
            this.noise_variances = new double[3];
            this.bias_variances = new double[3];
        }

        public IMUInfo(string frame_id, double[] data, double[] noise_variances, double[] bias_variances)
        {
            this.frame_id = frame_id;
            this.data = data;
            this.noise_variances = noise_variances;
            this.bias_variances = bias_variances;
        }
    }
}
